### ISSUE TITLE
Extract all strings from source files

### ISSUE THREAD

**Issue by dkastl** [hyakumori/smash#12]
We need to extract all strings from source files and place them in language files to continue with translation as in #3 

Checklist of source files:

- [ ] export_widget.dart
- [ ] geopackage_export.dart
- [ ] gpx_kml_export.dart
- [ ] gss_export.dart
- [ ] pdf_export.dart
- [x] form_smash_utils.dart
- [x] filters.dart
- [x] geocoding.dart
- [ ] gps.dart
- [x] testlog.dart
- [x] gss_utilities.dart
- [x] gss_import.dart
- [x] import_widget.dart
- [x] mainview.dart
- [x] mainview_utils.dart
- [ ] feature_attributes_viewer.dart
- [ ] layermanager.dart
- [ ] layersource.dart
- [ ] layersview.dart
- [ ] onlinesourcespage.dart
- [ ] remotedbpage.dart
- [ ] geoimage.dart
- [ ] geopackage.dart
- [ ] gpx.dart
- [ ] mapsforge.dart
- [ ] mbtiles.dart
- [ ] postgis.dart
- [ ] shapefile.dart
- [ ] tiles.dart
- [ ] wms.dart
- [ ] center_cross_plugin.dart
- [ ] current_log_plugin.dart
- [ ] feature_info_plugin.dart
- [ ] fences_plugin.dart
- [ ] gps_position_plugin.dart
- [ ] heatmap.dart
- [ ] pluginshandler.dart
- [ ] ruler_plugin.dart
- [ ] scale_plugin.dart
- [ ] gps_state.dart
- [ ] mapbuilder.dart
- [ ] map_state.dart
- [ ] project_state.dart
- [ ] geometryeditor_state.dart
- [ ] info_tool_state.dart
- [ ] ruler_state.dart
- [ ] tools.dart
- [ ] data_loader.dart
- [ ] images.dart
- [ ] images.dart
- [ ] logs.dart
- [ ] notes.dart
- [ ] othertables.dart
- [ ] project_database.dart
- [ ] projects_view.dart
- [ ] coachmarks.dart
- [ ] elevcolor.dart
- [ ] experimentals.dart
- [ ] fence.dart
- [ ] network.dart
- [ ] notifications.dart
- [ ] notifier.dart
- [ ] offline_maps.dart
- [ ] urls.dart
- [x] about.dart
- [ ] gps_info_button.dart
- [ ] gps_log_button.dart
- [ ] image_widgets.dart
- [ ] log_list.dart
- [ ] log_properties.dart
- [ ] note_list.dart
- [ ] note_properties.dart
- [ ] settings.dart
- [x] toolbar_tools.dart

**Comment by iosefa** [comment]
@sanak @mbasa-georepublic 

Can we close this issue? I take it that it was resolved (and all strings in the above listed files were extracted) in https://github.com/moovida/smash/pull/115

**Comment by iosefa** [comment]
ok, thanks for the confirmation 😄
