### ISSUE TITLE
Support tags.json download for all projects

### ISSUE THREAD

**Issue by dkastl** [hyakumori/smash#15]
After implementation of https://github.com/gtt-project/redmine_gtt_smash/issues/17 we can allow the download of all available tracker type schemas at once with project selection as part of the custom form.

This means we can keep the current project selection in GTT Settings, but we can add a checkbox to enable all possible projects as alternative.

If a user checks that checkbox, individual selection of a project will be disabled and the `tags.json` document is downloaded from the general API endpoint.

**Comment by dkastl** [comment]
@mbasa-georepublic , this is probably the last remaining feature for this phase development.

If the explanation above was not clear, there is an alternative endpoint now with the Redmine GTT SMASH plugin, that allows to get all tracker types of all projects:

```
http://localhost:3000/smash/tags.json 
```

Instead of the hidden `project_id` field with a preset value there is now a combobox field, which the user needs to select the project from in the custom note form.

So from the point of view of creating the isssues on sync the logic should be the same.
But on the  `IMPORT` screen the users should either download all tracker forms or just the ones of a single project.

**Comment by sanak** [comment]
I confirmed this, so I close this.
