### ISSUE TITLE
Failed to upload attachment images

### ISSUE THREAD

**Issue by sanak** [hyakumori/smash#22]
**Problem**
When I export form note which includes attachment images on Android Emulator (Pixel 2 API 27), attachment images were not uploaded.

**To Reproduce**
Take a photo on the form note, then export it.

**Expectation**
Attachment images should be uploaded.

**Platform/smartphone:**
 - Device: Android Emulator
 - OS: Android 8.1
 - App Version: latest (https://github.com/hyakumori/smash/commit/5d9b3f10e02789ffda9342e8444a37ccb04cef6b)

**Comment by sanak** [comment]
Well, I noticed that saved `attachments` value is empty before uploading data and this may come from the latest commit on upstream.
- https://github.com/moovida/smash/commit/01b3a85cf9e5e56d6496b0331f5fe7f8fac97018
- https://github.com/moovida/smashlibs/commit/032f9dd04666fb904fae320ae51a7564fd089fdd

**Comment by moovida** [comment]
@sanak , just to let you know that it is indeed a regression introduced by me. I am on it on solving it.

**Comment by sanak** [comment]
@moovida  (CC: @mbasa-georepublic, @iosefa, @dkastl)  
Okay, thanks for confirmation!

We are going to provide debug build apk at next Monday (or around middle of next week), so if possible, fix until this weekend is quite helpful for us... 🙇‍♂️ 

Also, we noticed that another boolean field type default value null issue, but I will check the cause to make sure.
https://github.com/gtt-project/redmine_gtt_smash/issues/26#issue-844316446

**Comment by moovida** [comment]
@sanak , I really hope to fix this by today. (actually I think I fixed it already, but need to make sure it uploads properly to the gss server).

If you have more info about the boolean issue please let me know. Today I will be able to fix everything that comes. Then not until Tuesday I think.

**Comment by moovida** [comment]
Actually, can I  push the changes in smash and smashlibs to master, so that you can also test it? It would be better to have your usecase also checked.

**Comment by sanak** [comment]
@moovida Thanks for quick response!

> Actually, can I push the changes in smash and smashlibs to master, so that you can also test it? It would be better to have your usecase also checked.

Oh, yes, please. 🙇‍♂️ 
Thanks!

**Comment by sanak** [comment]
@moovida (CC: @mbasa-georepublic, @iosefa, @dkastl)  
Thanks a lot!
I confirmed that attachment image issue was solved!

About boolean field issue, I noticed that our GTT server (and maybe our client?) side modification seems to be the cause, so we will fix it by ourselves.
- `redmine_gtt_smash`: https://github.com/gtt-project/redmine_gtt_smash/issues/26
- `hyakumori/smash`: https://github.com/hyakumori/smash/blob/gtt/main/lib/eu/hydrologis/smash/gtt/gtt_uilities.dart#L265

Latest `master` branch's form editing functionality was quite important for us, so really thanks for your quick fix!

**Comment by moovida** [comment]
Great. There is one more change coming in that touches forms. But it should not be an issue. I just had to add a key to the widgets of the forms, because on flutter web some widgets got reused and showed wrong stuff. Just as a heads up.

Good luck for your demo next week.

**Comment by sanak** [comment]
@moovida (CC: @mbasa-georepublic, @iosefa, @dkastl)
> There is one more change coming in that touches forms. But it should not be an issue. I just had to add a key to the widgets of the forms, because on flutter web some widgets got reused and showed wrong stuff. Just as a heads up.

Okay, thanks for sharing the information!

> Good luck for your demo next week.

Oh, yes. Thanks!
