### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by dkastl** [hyakumori/smash#3]
After #1 and #2 we need to translate all strings into Japanese.

**Comment by dkastl** [comment]
See https://github.com/moovida/smash/issues/2 for more information.

**Comment by sanak** [comment]
Well, I will check Google translated Japanese, once.

**Comment by sanak** [comment]
@mbasa-georepublic  (CC: @dkastl)  
To check Japanese translation quickly, I like to add changing locale functionality in `Settings` menu, but how do you think about that ?

List menu title (and subtitle) may be `Locale`, and page contents will be just `Locale` combo box which default value is `system locale` and other values are `en`/`it`/`ja`.

From the following official doc, changing locale seems to be possible,
https://pub.dev/packages/i18n_extension#changing-the-current-locale

QGIS 3.16 LTS has more menus, but I think that this level is not necessary.
<img width="1029" alt="qgis_localization" src="https://user-images.githubusercontent.com/629923/122011659-4d27c400-cdf7-11eb-82d7-352d74a15d05.png">

**Comment by dkastl** [comment]
I don't know. But I think having a language selection in the app settings would be also nice, with default to `auto`.

**Comment by sanak** [comment]
@mbasa-georepublic (CC: @dkastl)
About dynamic locale change, the following way may be available.
https://stackoverflow.com/questions/67106411/flutter-change-localization-programatically

I will try above, once from master branch.

Also, I will fix Japanese translation by https://mt-auto-minhon-mlt.ucri.jgn-x.jp/content/menu/ which is more OSS compatible for both upstream (master) and this fork (gtt/main) words.

**Comment by dkastl** [comment]
Shall we close this as Weblate seems to be setup, see #2 ?

**Comment by dkastl** [comment]
Localization can now take place on Weblate: https://hosted.weblate.org/projects/smash/smash-main-app/
