### ISSUE TITLE
2-way sync for issues

### ISSUE THREAD

**Issue by dkastl** [hyakumori/smash#33]
Currently it's only possible to create new GTT issues with SMASH.
Adding the ability to update existing issues would require some sort of 2-way sync:

- [ ] only create issue if it doesn't exist yet
- [ ] update issue, if it already exists
- [ ] keep issues in sync, when there is internet connection
- ~[ ] handle merge conflicts (in a simple way)~
- ~[ ] consider how to handle deleting/deleted issues~

**Comment by sanak** [comment]
This needs redmine_gtt_smash plugin side following id support.
https://github.com/gtt-project/redmine_gtt_smash/issues/28
