### ISSUE TITLE
"Quick" issue with image notes

### ISSUE THREAD

**Issue by dkastl** [hyakumori/smash#34]
It seems to be convenient to be able to create issues quickly with just an image and the current GPS position through SMASH's image note function.
However, Redmine GTT has some required fields and may have custom required fields as well.

This needs some discussion how to find a generic solution:
- specify a tracker type to be used for image notes, that must be available
- use "dummy" data for required fields like "Image not + date" for issue title
- otthers?

**Comment by sanak** [comment]
From 6/17(Thu) internal discussion, we will do the following:
- @sanak - Supports GTT Smash plugin side default tracker type
