### ISSUE TITLE
Sync status

### ISSUE THREAD

**Issue by dkastl** [hyakumori/smash#35]
It's not clear, if the synchronization (creation) of issues is completed or not.
SMASH uses a flag to indicate the upload status, but it's not possible for the user to see this information.

Possible ways to indicate the sync status:
- add an indicator to the issues
- have a sync status screen
- upload progress indication: which has been uploaded, which is not yet uploaded.
- others?

**Comment by sanak** [comment]
This needs redmine_gtt_smash plugin side following id support.
https://github.com/gtt-project/redmine_gtt_smash/issues/28
