### ISSUE TITLE
When importing "Single Project", creating form note fails by red screen

### ISSUE THREAD

**Issue by sanak** [hyakumori/smash#36]
**Problem**
When importing "Single Project", creating form note fails by red screen.

**To Reproduce**
1. Select "Single Project" in "Import"/"GTT" screen, then click "Import" button.
2. Return back to main screen, then tap form note button on the bottom tab.

**Expectation**
All available fields should be shown without red screen.

**Screenshots**
<img src="https://user-images.githubusercontent.com/629923/122152276-0049f900-ce9c-11eb-9566-c3527b511498.jpg" alt="Screenshot_20210608_125705_eu hydrologis smash" width="250px">

**Platform/smartphone:**

 - Device: ASUS_X00RD
 - OS: Android 8
 - App Version: 1.6.5+56_gtt

**Comment by mbasa** [comment]
default form values should be **String** and not **int**. 

The error is thrown the String function `trim` is called on an integer. From forms_widget.dart line 666: 

```dart
    String value = ""; //$NON-NLS-1$
    if (widget._itemMap.containsKey(TAG_VALUE)) {
      value = widget._itemMap[TAG_VALUE].trim();
    }
```

**Comment by sanak** [comment]
I fixed this issue at redmine_gtt_smash plugin side, so I close this.
