### ISSUE TITLE
When selecting original tags.json example section, uploaded issue's description looks bad

### ISSUE THREAD

**Issue by sanak** [hyakumori/smash#37]
**Problem**
When selecting original tags.json example section, uploaded issue's description looks bad

**To Reproduce**
1. Fresh install after deleting "smash" folder contents on the device.
2. Import "gtt_tags.json", but keep original "tags.json".
3. Tap form note button, then select "example" section.
4. Export to GTT.

Then Redmine side description field looks bad.
![exported_description](https://user-images.githubusercontent.com/629923/122153221-7f8bfc80-ce9d-11eb-86e7-101edf4f069c.png)

**Improvement**
How about to upload the contents as json attachment file ?

**Comment by dkastl** [comment]
Good idea for a solution?
to me it's not clear why a user would like to keep default `tags.json`, because this configuration is just an example.

**Comment by mbasa-georepublic** [comment]
**Reason**
when `GTT Export` encounters a form that it does not know how to handle, the form data is sent as is on the presumption that it will be useful to the user.

**Comment by dkastl** [comment]
Well, to me this `tags.json`, that is created automatically when you start SMASH for the first time, is really just an example to give people an idea, how they could make their own custom form.

In my opinion it has no other use case than that, and I would just delete it when the GTT tags.json is fetched from the server. I don't see any value in using it for SMASH users of GTT. it's just confusing for the usersbut useless.
If someone doesn't use GTT, then nothing will change. They can have the default examples.

If we are concerned to delete files, just renaming it is also fine, like `tags.json.20210101`.
