### ISSUE TITLE
GTT Server settings

### ISSUE THREAD

**Issue by dkastl** [hyakumori/smash#4]
Similar to the [GSS Settings](https://www.geopaparazzi.org/smash/index.html#_gss_settings) we want to add another screen to configure a GTT server.

This will require the following form fields:

- [x] Server URL
- [x] Login
- [x] Password
- [ ] (allow self-signed certificate)

**Comment by dkastl** [comment]
Better than storing username and password on the phone is to authenticate and fetch the user's API key and stored that key only on the phone.

**Comment by sanak** [comment]
@mbasa-georepublic (CC: @dkastl)
In my understanding, above `(allow self-signed certificate)` is not necessary, so I think that this can be closed.

**Comment by dkastl** [comment]
Yes, not necessary ... probably. Not sure exactly what use case needs that.

**Comment by moovida** [comment]
That one was necessary in case you have an https case but without a certificate given by an authority. That is the case of servers without a domain and hence need to be selfsigned.

In these cases the DIO library fails if not specifically set to allow selfsigned certificates. And I didn't want to have it enabled by default.

**Comment by mbasa-georepublic** [comment]
Removed certificate setting in the GTT setting screen and use the API Key instead of username/password when accessing the API server.
