### ISSUE TITLE
GTT project selection

### ISSUE THREAD

**Issue by dkastl** [hyakumori/smash#5]
After login (see #4 ) the list of available projects can be fetched from the GTT server and the user should choose one of them, probably from a dropdown list.

The Redmine `projects` APi endpoint should provide all functionality we need:
https://www.redmine.org/projects/redmine/wiki/Rest_Projects

```
GET /projects.xml?include=enabled_modules,trackers
```

This should include the modules enabled for each project, so we can filter those, where SMASH is enabled.

**Comment by mbasa-georepublic** [comment]
Project list is downloaded and is presented as a choice.
