### ISSUE TITLE
Fetch tags.json from GTT

### ISSUE THREAD

**Issue by dkastl** [hyakumori/smash#6]
When the user selected a project (see #5 ), the mobile app can request the configuration for the [custom notes](https://www.geopaparazzi.org/smash/index.html#_form_based_notes) from the GTT server via API as implemented in https://github.com/gtt-project/redmine_gtt_smash/issues/8

The JSON configuration can be fetched automatically when selecting a project, and we could also add a `Update Forms` button to manually trigger an update:

Question:
- What to do if there is an old (outdated) version of the configuration already? Do we need to ask the user what to do?
- Do we need "read-only" fields?
- Do we need to fetch other information?
- How to validate JSON?
- Where to place `tags.json`?
- Can we store multiple `.json` files?

**Comment by mbasa-georepublic** [comment]
Import SMASH forms from the server and write as `gtt_tags.json` in the device' forms directory.
