### ISSUE TITLE
Upload (sync) button

### ISSUE THREAD

**Issue by dkastl** [hyakumori/smash#8]
SMASH will mostly be used offline, so when a user connects to internet again, they can upload their notes by clicking a button.

Questions:
- What to do with notes after upload?
- How to make sure not to create duplicates, see #7 as an idea?
- Would be two-way synchronization hard?

**Comment by dkastl** [comment]
The way to upload data probably requires a new screen in `> Menu > Export > GTT` similar to how it is done with GSS.

**Comment by mbasa-georepublic** [comment]
An export function has been created  to upload forms when an internet connection can be made.
